# These are supported funding model platforms

github: [therealdreg]
patreon: dreg
custom: ["https://www.paypal.me/therealdreg"]
custom: ["https://blockchain.coinmarketcap.com/address/bitcoin/34or74iWCG9wHqonxBjxgPKargcTbAdJvi"]
